更多课程请关注：http://edu.51cto.com/lecturer/index/user_id-12330098.html<br>
QQ群：616043628<br>
微信公众号：深度学习与神经网络<br>
<img src="http://mp.weixin.qq.com/mp/qrcode?scene=10000004&size=102&__biz=MzIxMDQ3NzQ0Ng=="
style="width:150px;height:150px;float:left">

In [1]:
import numpy as np

In [2]:
#输入数据
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，取值范围-1到1
V = np.random.random((3,4))*2-1 
W = np.random.random((4,1))*2-1
print(V)
print(W)
#学习率设置
lr = 0.11

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):
    return x*(1-x)

def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
    
    L2_delta = (Y.T - L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    
    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C

[[ 0.42401878  0.42235789 -0.34470316  0.95723034]
 [-0.67478839  0.90315422 -0.4601116   0.06491045]
 [ 0.19164358  0.26754708 -0.1883737   0.56186385]]
[[-0.59738494]
 [-0.8307738 ]
 [ 0.72352953]
 [ 0.79658215]]


In [3]:
for i in range(20000):
    update()#更新权值
    if i%500==0:
        L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T-L2)))
        
L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
print(L2)

def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0

for i in map(judge,L2):
    print(i)

Error: 0.501081511208
Error: 0.497986166485
Error: 0.491947171292
Error: 0.467299538344
Error: 0.376507109212
Error: 0.253339266985
Error: 0.176367622003
Error: 0.134224330585
Error: 0.10898297383
Error: 0.0923802347072
Error: 0.0806602551864
Error: 0.0719428458153
Error: 0.0651966939017
Error: 0.0598125835622
Error: 0.0554086529673
Error: 0.0517337772589
Error: 0.0486161579598
Error: 0.0459343263304
Error: 0.0435999695628
Error: 0.0415473286499
Error: 0.03972641622
Error: 0.0380985421867
Error: 0.0366332812834
Error: 0.0353063684266
Error: 0.0340982069038
Error: 0.0329927908378
Error: 0.0319769136035
Error: 0.0310395773542
Error: 0.0301715464136
Error: 0.0293650051842
Error: 0.0286132930649
Error: 0.0279106968487
Error: 0.0272522865378
Error: 0.026633784316
Error: 0.0260514591013
Error: 0.0255020410215
Error: 0.0249826515424
Error: 0.024490745996
Error: 0.0240240660063
Error: 0.0235805998736
[[ 0.01504111]
 [ 0.97501612]
 [ 0.97607673]
 [ 0.02868923]]
0
1
1
0
